import type { Metadata } from 'next'
import { Glory } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const glory = Glory({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${glory.className} text-lg`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
